import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const wrapper = path.join(root, 'scripts/wp-env.mjs');

function wp(args, { allowFailure = false } = {}) {
  const result = spawnSync(process.execPath, [wrapper, 'run', 'cli', 'wp', ...args], {
    cwd: root,
    encoding: 'utf8',
    stdio: allowFailure ? 'pipe' : 'inherit',
  });
  if (!allowFailure && result.status !== 0) process.exit(result.status ?? 1);
  return result;
}

// Preserve administrator accounts and the configured signed-in test account.
// All other users, RSVP rows, forum topics/replies, and RSVP test-mail captures
// are generated by browser tests and are safe to remove from this local site.
const testUser = process.env.WP_TEST_USER || 'guest';
const usersResult = wp(['user', 'list', '--fields=ID,user_login,roles', '--format=json'], { allowFailure: true });
if (usersResult.status !== 0) {
  console.error(usersResult.stderr || 'Could not list local WordPress users.');
  process.exit(usersResult.status ?? 1);
}

let users;
try {
  users = JSON.parse(usersResult.stdout || '[]');
} catch {
  console.error('Could not parse the local WordPress user list.');
  process.exit(1);
}
const deleteIds = users
  .filter(user => user.user_login !== testUser && !String(user.roles ?? '').split(',').includes('administrator'))
  .map(user => String(user.ID))
  .filter(id => /^\d+$/.test(id));
if (deleteIds.length) wp(['user', 'delete', ...deleteIds, '--yes', '--reassign=1']);

wp([
  'eval',
  "global $wpdb; $table = $wpdb->prefix . 'at_rsvps'; if ($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s', $table)) === $table) { $wpdb->query('TRUNCATE TABLE ' . $table); } $posts = get_posts(array('post_type' => array('topic', 'reply'), 'post_status' => 'any', 'numberposts' => -1, 'fields' => 'ids')); foreach ($posts as $post_id) { wp_delete_post($post_id, true); } delete_transient('at_gathering_last_test_mail'); $wpdb->query(\"DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_at_gathering_form_%' OR option_name LIKE '_transient_timeout_at_gathering_form_%'\");",
]);

// Recreate/repair all canonical pages, plugin settings, and the seeded forum
// topic after removing browser-generated content.
const setup = spawnSync(process.execPath, [path.join(root, 'scripts/setup-local.mjs')], {
  cwd: root,
  stdio: 'inherit',
  env: process.env,
});
if (setup.status !== 0) process.exit(setup.status ?? 1);
